# docker-compose.yml
version: '3.8'
services:
  flask:
    build: .
    command: gunicorn -w 4 -b :8000 app:app
    container_name: opengsq-master-server-flask
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    ports:
      - 8000:8000

  schedule:
    build: .
    command: python main.py
    container_name: opengsq-master-server-schedule
    env_file:
      - .env
