# docker-compose.yml
version: '3.8'
services:
  flask:
    build: .
    command: gunicorn -w 4 -b :8000 app:app
    container_name: opengsq-master-server-flask
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    ports:
      - ${PORT}:8000
    restart: always
    volumes:
      - flask_monitoringdashboard.db:flask_monitoringdashboard.db

  schedule:
    build: .
    command: python -u main.py
    container_name: opengsq-master-server-schedule
    env_file:
      - .env
    restart: always
